const STORAGE_KEY = "hesi-smoo-v0.1";
const APPLICATION_DEADLINE = new Date("2026-10-22T23:59:00");
const plans = {
  5: { duration:"5 min", title:"Do a five-minute rescue.", start:"START 5-MIN SESSION", note:"Three useful retrievals. Then you are released.", pill:"DO THIS NOW", subject:"Vocabulary maintenance", labels:["Vocab rescue","One math item","Reading passage"], route:["3 words · retrieval","Only if more brain appears","Not today"], states:["NOW","BONUS","LATER"] },
  15:{ duration:"15 min", title:"Start with vocabulary.", start:"START 15-MIN SESSION", note:"This round is enough. More work is available, not owed.", pill:"DO THIS NOW", subject:"Vocabulary retrieval", labels:["Vocab sprint","Math block","Reading passage"], route:["6 words · retrieval","If more brain appears","Not owed"], states:["NOW","BONUS","OPTIONAL"] },
  30:{ duration:"30 min", title:"Vocab, then one math set.", start:"START 30-MIN SESSION", note:"The app has already sequenced the half hour.", pill:"DO THIS NOW", subject:"Vocabulary + math", labels:["Vocab sprint","Math block","Reading passage"], route:["8 words · retrieval","2 worked items","If capacity remains"], states:["NOW","NEXT","OPTIONAL"] },
  full:{ duration:"open", title:"Start the full route.", start:"START FULL SESSION", note:"Vocab → math until tired → one reading passage if there’s gas.", pill:"DO THIS NOW", subject:"Full HESI route", labels:["Vocab sprint","Math block","Reading passage"], route:["10 words · retrieval","3 worked items","One passage"], states:["NOW","NEXT","OPTIONAL"] }
};
const apPlan = { duration:"5–10 min", title:"Take the HESI minimum dose.", start:"START MINIMUM DOSE", note:"Then close HESI Smoo and go study anatomy. The app means it.", pill:"A&P-PROTECTED", subject:"HESI maintenance", labels:["HESI maintenance","One bonus item","Return to A&P"], route:["3-word retrieval rescue","Only if genuinely easy","A&P gets the next block"], states:["NOW","OPTIONAL","STOP"] };

// Canonical bank shared with the dedicated topic pages.
const { vocabItems: vocab, mathItems: math, readingItems: reading } = window.HESI_BANK;

const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
function feedFish(){const fish=$("#fishy"),food=$("#fish-food");if(!fish||!food)return;document.body.classList.remove("fish-fed");void document.body.offsetWidth;document.body.classList.add("fish-fed");clearTimeout(window.fishFoodTimer);window.fishFoodTimer=setTimeout(()=>document.body.classList.remove("fish-fed"),1100)}
const dateKey=()=>new Date().toISOString().slice(0,10);
const empty=()=>({version:2,capacity:"15",logistics:{sections:true,scheduling:false,retake:false,deadline:true},dailyContext:{date:dateKey(),heavyAP:false},ratings:{},itemHistory:{},sessions:[]});
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!s)return empty();const d=s.dailyContext?.date===dateKey()?s.dailyContext:{date:dateKey(),heavyAP:false};return {...empty(),...s,version:2,ratings:s.ratings||{},itemHistory:s.itemHistory||{},dailyContext:d,logistics:{...empty().logistics,...s.logistics}}}catch{return empty()}}
let state=load(), cap=state.capacity, heavy=!!state.dailyContext.heavyAP, vRound=[],vIndex=0,vRatings=[],mRound=[],mIndex=0,mAnswers=[],rItem=null,rAnswer=null,blocks=[],toastTimer,installPrompt;
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
const activePlan=()=>heavy?apPlan:plans[cap];
const vCount=()=>heavy||cap==="5"?3:cap==="15"?6:cap==="30"?8:10;
const mCount=()=>cap==="full"?3:cap==="30"?2:1;
const hist=id=>state.itemHistory[id]||{attempts:0,correct:0,wrong:0};
const pick=(items,n,score)=>[...items].sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id)).slice(0,n);
const vScore=i=>{const r=state.ratings[i.id]||{again:0,hard:0,gotIt:0};return r.again*4+r.hard*2-r.gotIt*.35};
const qScore=i=>{const h=hist(i.id);return h.wrong*4-h.correct*.45+(h.attempts?0:1)};
const stat=(n,label)=>`<div class="stat-tile"><strong>${n}</strong><small>${label}</small></div>`;
function setDates(){const days=Math.max(0,Math.ceil((APPLICATION_DEADLINE-new Date())/86400000));$("#today-label").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"short",day:"numeric"}).format(new Date());$("#days-to-target").textContent=`${days} ${days===1?"day":"days"} to application deadline`;$("#test-date-note").textContent=state.logistics.scheduling?"HESI appointment marked confirmed":"HESI date unconfirmed · schedule within the current two-week window";}
function view(name){$$(".view").forEach(x=>{x.hidden=x.dataset.view!==name;x.classList.toggle("active",!x.hidden)});$$(".nav-button").forEach(x=>{const on=x.dataset.nav===name;x.classList.toggle("active",on);on?x.setAttribute("aria-current","page"):x.removeAttribute("aria-current")});history.replaceState(null,"",`#${name}`);window.scrollTo({top:0,behavior:"smooth"})}
function panel(name){$$(".session-panel").forEach(x=>{x.hidden=x.dataset.sessionPanel!==name;x.classList.toggle("active",!x.hidden)});const h={vocab:[`VOCAB · ${activePlan().duration.toUpperCase()} PLAN`,"Try it before you reveal it.",`${vIndex+1} / ${vRound.length}`,8],"vocab-complete":["VOCAB · COMPLETE","First block closed.","1 / 3",34],math:["MATH · WORKED PRACTICE","Choose, then read the mechanism.",`${mIndex+1} / ${mRound.length}`,48],capacity:["CHECK CAPACITY","Choose the truthful stopping point.","2 / 3",67],reading:["READING · ONE PASSAGE","Accuracy first. Timing later.","3 / 3",78],complete:["SESSION · COMPLETE","The next move can wait.","DONE",100]}[name];$("#session-kind").textContent=h[0];$("#session-title").textContent=h[1];$("#session-counter").textContent=h[2];$("#session-progress-bar").style.width=`${h[3]}%`;}
function renderPlan(){const p=activePlan();$$("[data-capacity]").forEach(b=>{const s=b.dataset.capacity===cap;b.classList.toggle("selected",s);b.setAttribute("aria-checked",s)});$("#now-pill").textContent=p.pill;$("#next-subject-label").textContent=p.subject;$("#session-duration").textContent=p.duration;$("#next-title").textContent=p.title;$("#start-label").textContent=p.start;$("#after-note").textContent=p.note;$$(".route-item").forEach((x,i)=>{x.classList.remove("complete","current");if(!i)x.classList.add("current");x.querySelector(".route-number").textContent=i+1;x.querySelector(".route-copy strong").textContent=p.labels[i];x.querySelector(".route-copy small").textContent=p.route[i];x.querySelector(".route-state").textContent=p.states[i]});markRoute()}
function renderHeavy(){const b=$("#ap-load-toggle");b.classList.toggle("active",heavy);b.setAttribute("aria-pressed",heavy);b.querySelector(".ap-toggle-box").textContent=heavy?"✓":"";$("#ap-toggle-state").textContent=heavy?"Yes":"No";}
function renderLogistics(){const n=Object.values(state.logistics).filter(Boolean).length,p=state.logistics.scheduling?0:1;$("#logistics-count").textContent=`${n} / 4 known${p?" · 1 pending":""}`;$$("[data-logistics]").forEach(b=>{const k=b.dataset.logistics,d=!!state.logistics[k],pending=k==="scheduling"&&!d;b.classList.toggle("complete",d);b.classList.toggle("pending",pending);b.setAttribute("aria-pressed",d);b.querySelector(".check-box").textContent=d?"✓":pending?"…":""})}
function renderQueue(){const records=[...math,...reading].map(i=>({label:i.topic||i.type,...hist(i.id)})).filter(i=>i.attempts).sort((a,b)=>(b.wrong*3-b.correct)-(a.wrong*3-a.correct));$("#queue-count").textContent=records.length?`${records.length} measured`:"Starting map";const initial=["Fraction conversion","Decimal operations","Percent","Main idea vs. detail"];$("#weak-queue").innerHTML=(records.length?records.slice(0,4).map((i,n)=>[i.label,`${i.wrong} miss${i.wrong===1?"":"es"} · returns sooner`]):initial.map((label,n)=>[label,n<2?"Known starting focus":"Will enter after evidence"])).map(([label,sub],n)=>`<li${n>1&&!records.length?' class="muted-row"':""}><span class="queue-rank">${String(n+1).padStart(2,"0")}</span><div><strong>${label}</strong><small>${sub}</small></div><span class="queue-action">${records.length?"PRACTICE":"NEXT"}</span></li>`).join("");}
function summary(s){const c=s.vocab.counts,m=s.math?` Math: ${s.math.items.filter(i=>i.correct).length}/${s.math.items.length} correct.`:"",r=s.reading?` Reading: ${s.reading.type} ${s.reading.correct?"correct":"needed correction"}.`:"";return `HESI Smoo — ${plans[s.capacity||"15"].duration} plan; ${s.blocks.join(", ")}. Vocab: ${c.gotIt} got it, ${c.hard} hard, ${c.again} again.${m}${r}${s.heavyAP?" A&P-protected minimum-dose day.":""}`;}
function renderStored(){const latest=state.sessions[0],v=Object.values(state.ratings).reduce((a,r)=>({again:a.again+r.again,hard:a.hard+r.hard,gotIt:a.gotIt+r.gotIt}),{again:0,hard:0,gotIt:0});$("#vocab-readiness").textContent=v.again+v.hard+v.gotIt?`${v.gotIt} successful retrievals`:"No estimate yet";for(const [id,items] of [["math-readiness",math],["reading-readiness",reading]]){const x=items.reduce((a,i)=>({a:a.a+hist(i.id).attempts,c:a.c+hist(i.id).correct}),{a:0,c:0});$("#"+id).textContent=x.a?`${x.c} / ${x.a} correct in practice`:"No estimate yet"}if(!latest){$("#recent-session-empty").hidden=false;$("#recent-session-list").hidden=true;$("#share-title").textContent="Nothing to send yet.";$("#share-summary").textContent="Complete a session and this becomes a clean, copyable study report.";return}$("#recent-session-empty").hidden=true;$("#recent-session-list").hidden=false;$("#recent-session-list").innerHTML=state.sessions.slice(0,4).map(s=>{const when=new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(s.completedAt)),returns=s.vocab.counts.again+s.vocab.counts.hard;return `<li><div><strong>${s.blocks.join(" + ")}</strong><small>${when} · ${returns} vocab ${returns===1?"item":"items"} to revisit</small></div><span class="session-score">${s.blocks.length} ${s.blocks.length===1?"block":"blocks"}</span></li>`}).join("");$("#share-title").textContent=`${latest.blocks.length} ${latest.blocks.length===1?"block":"blocks"} completed.`;$("#share-summary").textContent=summary(latest);}
function markRoute(){const s=state.sessions[0];if(!s||new Date(s.completedAt).toDateString()!==new Date().toDateString())return;$$(".route-item").forEach(x=>{const map={vocab:"Vocabulary",math:"Math",reading:"Reading"};if(s.blocks.includes(map[x.dataset.routeStep])){x.classList.add("complete");x.classList.remove("current");x.querySelector(".route-number").textContent="✓";x.querySelector(".route-state").textContent="DONE"}})}
function resetSession(){vIndex=0;vRatings=[];mRound=[];mIndex=0;mAnswers=[];rItem=null;rAnswer=null;blocks=[];}
function showSessionShell(){$("#session-shell").hidden=false;document.body.classList.add("session-open");$("#close-session").focus();}
function openSession(){resetSession();vRound=pick(vocab,vCount(),vScore);renderV();panel("vocab");showSessionShell();}
function openTopic(value){resetSession();const [lane,topic]=value.split(":");if(lane==="vocab"){vRound=pick(vocab,vCount(),vScore);renderV();panel("vocab");}else if(lane==="math"){startMath(topic);}else{startReading(topic);}showSessionShell();}
function closeSession(){$("#session-shell").hidden=true;document.body.classList.remove("session-open");$("#start-session").focus();}
function renderV(){const x=vRound[vIndex];$("#vocab-word").textContent=x.word;$("#vocab-example").textContent=`“${x.example}”`;$("#vocab-answer").textContent=x.answer;$("#answer-area").hidden=true;$("#rating-area").hidden=true;$("#reveal-answer").hidden=false;$("#session-counter").textContent=`${vIndex+1} / ${vRound.length}`;$("#session-progress-bar").style.width=`${8+vIndex/vRound.length*24}%`;}
function rate(rating){const x=vRound[vIndex];vRatings.push({itemId:x.id,word:x.word,rating});if(rating==="got-it")feedFish();if(++vIndex<vRound.length){renderV();return}blocks.push("Vocabulary");const c=countRatings();const n=c.again+c.hard;$("#vocab-completion-title").textContent=n?`Nice—we found ${n} ${n===1?"word":"words"} worth learning.`:"Clean retrieval. These can get out of your way.";$("#vocab-result-copy").textContent=n?`${n} ${n===1?"word is":"words are"} now queued to return sooner. The search worked.`:"These words can now return less often, not disappear forever.";$("#vocab-stats").innerHTML=[stat(c.again,"Again"),stat(c.hard,"Hard"),stat(c.gotIt,"Got it")].join("");const short=heavy||cap==="5"||cap==="15";$("#continue-math span:first-child").textContent=heavy?"FINISH HESI · GO TO A&P":short?"FINISH TODAY":"CONTINUE TO MATH";$("#continue-math span:last-child").textContent=short?"✓":"→";$("#stop-after-vocab").textContent=heavy?"I truly have more brain → one math item":short?"I found more brain → Math":"Stop here—this still counts";panel("vocab-complete");}
function countRatings(){return vRatings.reduce((a,r)=>{a[r.rating==="got-it"?"gotIt":r.rating]++;return a},{again:0,hard:0,gotIt:0})}
function startMath(topic){const pool=topic?math.filter(x=>x.topic===topic):math;mRound=pick(pool.length?pool:math,mCount(),qScore);mIndex=0;mAnswers=[];renderMath();panel("math");}
function choices(el,values,fn){el.innerHTML="";values.forEach((v,i)=>{const b=document.createElement("button");b.type="button";b.textContent=v;b.addEventListener("click",()=>fn(i,b));el.append(b)})}
function renderMath(){const x=mRound[mIndex];$("#math-instruction").textContent=`${x.topic.toUpperCase()} · ORIGINAL PRACTICE`;$("#math-prompt").textContent=x.prompt;$("#math-feedback").hidden=true;$("#math-next").hidden=true;$("#math-next span:first-child").textContent=mIndex+1===mRound.length?"MATH BLOCK DONE":"NEXT MATH ITEM";choices($("#math-choices"),x.choices,answerMath);$("#session-counter").textContent=`${mIndex+1} / ${mRound.length}`;}
function record(x,correct){const h=state.itemHistory[x.id]||{attempts:0,correct:0,wrong:0,topic:x.topic||x.type};h.attempts++;h[correct?"correct":"wrong"]++;h.topic=x.topic||x.type;state.itemHistory[x.id]=h;save();}
function answerMath(i,b){if(mAnswers[mIndex])return;const x=mRound[mIndex],correct=x.choices[i]===x.answer;mAnswers[mIndex]={id:x.id,topic:x.topic,correct};record(x,correct);$$("#math-choices button").forEach(q=>{q.disabled=true;if(q.textContent===x.answer)q.classList.add("selected-correct")});if(!correct)b.classList.add("selected-wrong");if(correct)feedFish();$("#math-feedback").hidden=false;$("#math-feedback").textContent=(correct?"Correct. ":"Useful—we found the procedure to reinforce. ")+x.explanation;$("#math-next").hidden=false;}
function nextMath(){if(++mIndex<mRound.length){renderMath();return}blocks.push("Math");heavy?finish("math"):panel("capacity");}
function startReading(topic){const pool=topic?reading.filter(x=>x.topic===topic):reading;rItem=pick(pool.length?pool:reading,1,qScore)[0];rAnswer=null;$("#reading-instruction").textContent=`${rItem.topic.toUpperCase()} · ORIGINAL PASSAGE`;$("#reading-passage").textContent=rItem.passage;$("#reading-prompt").textContent=rItem.prompt;$("#reading-feedback").hidden=true;$("#reading-next").hidden=true;choices($("#reading-choices"),rItem.choices,answerReading);panel("reading");}
function answerReading(i,b){if(rAnswer)return;const correct=i===rItem.answer;rAnswer={id:rItem.id,type:rItem.topic,correct};record(rItem,correct);$$("#reading-choices button").forEach((q,n)=>{q.disabled=true;if(n===rItem.answer)q.classList.add("selected-correct")});if(!correct)b.classList.add("selected-wrong");if(correct)feedFish();$("#reading-feedback").hidden=false;$("#reading-feedback").textContent=(correct?"Correct. ":"Useful—we found the distinction to practice. ")+rItem.explanation;$("#reading-next").hidden=false;}
function finish(stop){const c=countRatings();vRatings.forEach(r=>{const x=state.ratings[r.itemId]||{again:0,hard:0,gotIt:0};x[r.rating==="got-it"?"gotIt":r.rating]++;state.ratings[r.itemId]=x});const s={id:crypto.randomUUID?.()||`s-${Date.now()}`,completedAt:new Date().toISOString(),capacity:cap,heavyAP:heavy,stoppedAfter:stop,blocks:[...blocks],vocab:{cards:vRatings,counts:c},math:mAnswers.length?{items:mAnswers}:null,reading:rAnswer};state.sessions.unshift(s);state.sessions=state.sessions.slice(0,50);save();$("#final-title").textContent=heavy?"HESI minimum dose: complete.":blocks.length===1?"One useful block: complete.":`${blocks.length} useful blocks: complete.`;$("#final-copy").textContent=heavy?"Close HESI Smoo. A&P gets the next block; protecting the 4.0 is part of the strategy.":"The evidence is saved on this device and ready for Nichole mode.";$("#final-summary").innerHTML=[stat(blocks.length,blocks.length===1?"Block":"Blocks"),stat(c.again+c.hard,"Words to return"),stat(rAnswer?"Yes":"No","Reading")].join("");renderStored();renderQueue();panel("complete");}
function toast(t){const x=$("#toast");x.textContent=t;x.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.hidden=true,2400)}
function bind(){$$(".nav-button").forEach(b=>b.addEventListener("click",()=>view(b.dataset.nav)));$(".brand").addEventListener("click",e=>{e.preventDefault();view("today")});$("#start-session").addEventListener("click",openSession);$$("[data-capacity]").forEach(b=>b.addEventListener("click",()=>{cap=b.dataset.capacity;state.capacity=cap;save();renderPlan()}));$("#ap-load-toggle").addEventListener("click",()=>{heavy=!heavy;state.dailyContext={date:dateKey(),heavyAP:heavy};save();renderPlan();renderHeavy()});$$("[data-logistics]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.logistics;state.logistics[k]=!state.logistics[k];save();renderLogistics();setDates()}));$("#close-session").addEventListener("click",closeSession);$("#reveal-answer").addEventListener("click",()=>{$("#reveal-answer").hidden=true;$("#answer-area").hidden=false;$("#rating-area").hidden=false});$$("[data-rating]").forEach(b=>b.addEventListener("click",()=>rate(b.dataset.rating)));$("#continue-math").addEventListener("click",()=>heavy||cap==="5"||cap==="15"?finish("vocab"):startMath());$("#stop-after-vocab").addEventListener("click",()=>heavy||cap==="5"||cap==="15"?startMath():finish("vocab"));$("#math-next").addEventListener("click",nextMath);$("#continue-reading").addEventListener("click",startReading);$("#finish-after-math").addEventListener("click",()=>finish("math"));$("#reading-next").addEventListener("click",()=>{blocks.push("Reading");finish("reading")});$("#return-today").addEventListener("click",()=>{closeSession();markRoute();view("today")});$("#copy-summary").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(state.sessions[0]?summary(state.sessions[0]):"HESI Smoo: no completed session yet.");toast("Summary copied.")}catch{toast("Copy was blocked. Try Download data instead.")}});$("#download-results").addEventListener("click",()=>{const b=new Blob([JSON.stringify({app:"HESI Smoo",version:"0.3-content-pack",exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`hesi-smoo-results-${dateKey()}.json`;a.click();URL.revokeObjectURL(u);toast("Results downloaded.")});$("#reset-prototype").addEventListener("click",()=>{if(!confirm("Reset all HESI Smoo data on this device?"))return;state=empty();cap=state.capacity;heavy=false;save();renderPlan();renderHeavy();renderLogistics();renderStored();renderQueue();setDates();toast("Study data reset.")});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("#session-shell").hidden)closeSession()})}
function init(){state.lastOpenedAt=new Date().toISOString();save();setDates();bind();$$("[data-study-topic]").forEach(b=>b.addEventListener("click",()=>openTopic(b.dataset.studyTopic)));renderPlan();renderHeavy();renderLogistics();renderStored();renderQueue();const h=location.hash.slice(1);view(["today","progress","coach"].includes(h)?h:"today");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#install-button").hidden=false});$("#install-button").addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#install-button").hidden=true});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js",{updateViaCache:"none"}).catch(()=>{}));}
init();
